server:
  port: 80


spring:
  application:
    # 微服务相互调用，这个项目中意义不大
    name: sob_blog_system
  datasource:
    url: jdbc:mysql://192.168.43.131:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    
# jpa 显示sql语句
  jpa:
    show-sql: true